# Generated by Django 5.2.4 on 2025-07-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParqueNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, help_text='Área en km²', null=True)),
                ('fecha_establecimiento', models.DateField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('wikidata_id', models.CharField(max_length=50, unique=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parque Nacional',
                'verbose_name_plural': 'Parques Nacionales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('wikidata_id', models.CharField(max_length=50, unique=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plaza',
                'verbose_name_plural': 'Plazas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('poblacion', models.IntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, help_text='Área en km²', null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('bandera_url', models.URLField(blank=True, null=True)),
                ('escudo_url', models.URLField(blank=True, null=True)),
                ('wikipedia_url', models.URLField(blank=True, null=True)),
                ('wikidata_id', models.CharField(max_length=50, unique=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SitioPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('UNESCO', 'Patrimonio Mundial UNESCO'), ('ARQUEOLOGICO', 'Sitio Arqueológico'), ('HISTORICO', 'Centro Histórico')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('wikidata_id', models.CharField(max_length=50, unique=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sitio Patrimonial',
                'verbose_name_plural': 'Sitios Patrimoniales',
                'ordering': ['nombre'],
            },
        ),
    ]
