# Generated by Django 5.2.4 on 2025-07-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecuador_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincia',
            name='cantones',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
