# Generated by Django 5.2.4 on 2025-07-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecuador_data', '0002_provincia_cantones'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='altura',
            field=models.FloatField(blank=True, help_text='Altura en metros', null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='area',
            field=models.FloatField(blank=True, help_text='Área en m²', null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='arquitecto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='capacidad',
            field=models.IntegerField(blank=True, help_text='Capacidad de personas', null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='categoria',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='commons_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='criterios_unesco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='detalles_enriquecidos',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='elevacion',
            field=models.FloatField(blank=True, help_text='Elevación sobre nivel del mar', null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='estado_conservacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='estatus_patrimonial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='estilo_arquitectonico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='fecha_inscripcion_unesco',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='numero_unesco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='provincia',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='subtipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='superficie',
            field=models.FloatField(blank=True, help_text='Superficie en hectáreas', null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='visitantes_anuales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitiopatrimonial',
            name='wikipedia_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitiopatrimonial',
            name='nombre',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sitiopatrimonial',
            name='tipo',
            field=models.CharField(choices=[('UNESCO', 'Patrimonio Mundial UNESCO'), ('ARQUEOLOGICO', 'Sitio Arqueológico'), ('HISTORICO', 'Centro Histórico'), ('RELIGIOSO', 'Patrimonio Religioso'), ('MUSEO', 'Museo'), ('MONUMENTO', 'Monumento'), ('FORTIFICACION', 'Fortificación'), ('PALACIO', 'Palacio'), ('BIBLIOTECA', 'Biblioteca Histórica'), ('TEATRO', 'Teatro Histórico'), ('MERCADO', 'Mercado Tradicional')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='sitiopatrimonial',
            index=models.Index(fields=['tipo', 'provincia'], name='ecuador_dat_tipo_472cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='sitiopatrimonial',
            index=models.Index(fields=['categoria', 'fecha_creacion'], name='ecuador_dat_categor_a32f12_idx'),
        ),
        migrations.AddIndex(
            model_name='sitiopatrimonial',
            index=models.Index(fields=['estatus_patrimonial'], name='ecuador_dat_estatus_bf7110_idx'),
        ),
    ]
