# Generated by Django 5.2.4 on 2025-07-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecuador_data', '0003_sitiopatrimonial_altura_sitiopatrimonial_area_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sitiopatrimonial',
            name='ecuador_dat_categor_a32f12_idx',
        ),
        migrations.RemoveField(
            model_name='sitiopatrimonial',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='sitiopatrimonial',
            name='area',
        ),
        migrations.RemoveField(
            model_name='sitiopatrimonial',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='sitiopatrimonial',
            name='elevacion',
        ),
        migrations.RemoveField(
            model_name='sitiopatrimonial',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='sitiopatrimonial',
            name='superficie',
        ),
        migrations.RemoveField(
            model_name='sitiopatrimonial',
            name='visitantes_anuales',
        ),
        migrations.AddIndex(
            model_name='sitiopatrimonial',
            index=models.Index(fields=['categoria', 'fecha_inicio'], name='ecuador_dat_categor_b8d0df_idx'),
        ),
    ]
