# Generated by Django 5.2.4 on 2025-07-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecuador_data', '0004_remove_empty_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaza',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
